;;; meson-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from meson-mode.el

(autoload 'meson-mode "meson-mode" "\
Major mode for editing Meson build system files.
\\{meson-mode-map}

(fn)" t)
(add-to-list 'auto-mode-alist '("/meson\\(\\.build\\|_options\\.txt\\)\\'" . meson-mode))
(eval-after-load 'compile '(progn (add-to-list 'compilation-error-regexp-alist 'meson) (add-to-list 'compilation-error-regexp-alist-alist '(meson "^Meson encountered an error in file \\(.*\\), line \\([0-9]+\\), column \\([0-9]+\\):" 1 2 3))))
(register-definition-prefixes "meson-mode" '("meson-"))


;;; Generated autoloads from utils.el

(register-definition-prefixes "utils" '("py2el" "refman2func-doc"))

;;; End of scraped data

(provide 'meson-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; meson-mode-autoloads.el ends here
